export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const PASSWORD_CONFIRMATION_CHANGED = 'PASSWORD_CONFIRMATION_CHANGED';
export const FIRSTNAME_CHANGED = 'FIRSTNAME_CHANGED';
export const LASTNAME_CHANGED = 'LASTNAME_CHANGED';
export const USER_PHOTO_CHANGED = 'USER_PHOTO_CHANGED';

export const ATTEMPT_USER_LOGIN = 'ATTEMPT_USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const ATTEMPT_USER_REGISTER = 'ATTEMPT_USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
