export const ATTEMPT_GETTING_ITEMS = 'ATTEMPT_GETTING_ITEMS';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAIL = 'GET_ITEMS_FAIL';

export const ATTEMPT_GETTING_ITEM = 'ATTEMPT_GETTING_ITEM';
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const GET_ITEM_FAIL = 'GET_ITEM_FAIL';
