export const GET_ITEMS_FAIL = 'GET_ITEMS_FAIL';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const ATTEMPT_GETTING_ITEMS = 'ATTEMPT_GETTING_ITEMS';

export const GET_ITEM_FAIL = 'GET_ITEM_FAIL';
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const ATTEMPT_GETTING_ITEM = 'ATTEMPT_GETTING_ITEM';

export const ITEM_SELECTED = 'ITEM_SELECTED';

export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ATTEMPT_ADDING_ITEM = 'ATTEMPT_ADDING_ITEM';

export const ITEM_NAME_CHANGED = 'ITEM_NAME_CHANGED';
export const ITEM_QUANTITY_CHANGED = 'ITEM_QUANTITY_CHANGED';
export const ITEM_UNIT_PRICE_CHANGED = 'ITEM_UNIT_PRICE_CHANGED';
export const ITEM_WHOLE_PRICE_CHANGED = 'ITEM_WHOLE_PRICE_CHANGED';
