export const JACKPOT_NAME_CHANGED = 'JACKPOT_NAME_CHANGED';
export const JACKPOT_AMOUNT_CHANGED = 'JACKPOT_AMOUNT_CHANGED';

export const GET_ALL_JACKPOTS_FAIL = 'GET_ALL_JACKPOTS_FAIL';
export const GET_ALL_JACKPOTS_SUCCESS = 'GET_ALL_JACKPOTS_SUCCESS';
export const ATTEMPT_GETTING_ALL_JACKPOTS = 'ATTEMPT_GETTING_ALL_JACKPOTS';

export const ADD_NEW_JACKPOT_FAIL = 'ADD_NEW_JACKPOT_FAIL';
export const ADD_NEW_JACKPOT_SUCCESS = 'ADD_NEW_JACKPOT_SUCCESS';
export const ATTEMPT_ADDING_NEW_JACKPOT = 'ATTEMPT_ADDING_NEW_JACKPOT';